# This is a basic workflow to help you get started with Actions

name: deploy Website

# Controls when the action will run. 
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploying to surge
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
            version: 12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Creating build
        run: npm run-script build

      - name: Installing surge
        run: npm install -g surge

      - name: deploying on surge
        run: surge ./build messy-rest.surge.sh --token ${{secrets.SURGE_TOKEN_SECRET}} 
